### ISSUE TITLE
i_can_count issue with gdb script

### ISSUE THREAD

**Issue by lucascebertin** [Pusty/writeups#1]
While trying to reproduce your gdb script, at the line 13 there is the flag_bug getting an ordinal value ...

```
gdb.execute("p flag_buf@1 = 0x%02X" % ord(c)) # set the first buffer character
```

When there, the script hangs up with this error:
`'flag_buf' has unknown type; cast it to its declared type`.

Should this thing happen?

I tried to execute this way:
```bash
gdb ./i_can_count_8484ceff57cb99e3bdb3017f8c8a2467
source script.py
```

Where script.py has your gdb script source code.

Could you help me with that?
Thanks :)

**Comment by lucascebertin** [comment]
Don't know if this is right but, changed a little bit and it's working:
From: 
```
gdb.execute("p flag_buf@1 = 0x%02X" % ord(c)) # set the first buffer character
```
To: 
```
gdb.execute("set *((char *) &flag_buf) = 0x%02X" % ord(c)) # set the first buffer character
```

and

From:
```
    cmp = int(gdb.parse_and_eval("*((unsigned char*)(check_buf + "+str(i)+"))")) # check buffer value for the given index

```

To:
```
    cmp = int(gdb.parse_and_eval("*((unsigned char*)check_buf+"+str(i) + ")")) # check buffer value for the given index
```

That's it, thanks!

**Comment by Pusty** [comment]
Just tested in on another system and the original works fine for me on

    GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
    GNU gdb (Debian 7.12-6) 7.12.0.20161007-git

Good to know this can cause problems, I will try to avoid it next time.
